---
  - name: Common | Update server
    apt: update_cache=yes
    tags: common

  - name: Common | Install cUrl
    apt: name=curl state=present update_cache=yes
    tags: common

  - name: Common | Install python-pycurl
    apt: name=python-pycurl state=present update_cache=yes cache_valid_time=600
    tags: common
